# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
unsafe = true

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true

[tableOfContents]
startLevel = 2
endLevel = 3
